### ISSUE TITLE
Set initial value on bind

### ISSUE THREAD

**Issue by nkbt** [kof/cyclic#3]
``` javascript
buffer.percent = 0;

cyclic
  .bind(buffer, 'percent')
  .to($scope, 'percent');

console.log("$scope.percent =", $scope.percent); 

// EXPECTED => $scope.percent = 0
// ACTUAL => $scope.percent = undefined
```

**Comment by kof** [comment]
must be a bug, will add a test

**Comment by kof** [comment]
did you call the .run function?

**Comment by nkbt** [comment]
Not manually. It is running in requestAnimationFrame loop

**Comment by kof** [comment]
maybe its not running for some reason, cause I have a test for this usecase and its passing https://github.com/kof/cyclic/blob/master/test/binding.js#L10

**Comment by kof** [comment]
are you logging at wrong time point?

**Comment by nkbt** [comment]
This one works. 

I think it should be applied "by default"

``` javascript
buffer.percent = 0;

cyclic
  .bind(buffer, 'percent')
  .to($scope, 'percent');
cyclic.run()

console.log("$scope.percent =", $scope.percent); 

// => $scope.percent = 0
```

**Comment by kof** [comment]
it is applied by default, you are just not waiting for your own .run call :)

**Comment by kof** [comment]
you mean to apply it synchronousely ...

**Comment by kof** [comment]
Thought about it again. If I apply the changes for the complete binding chain immediately, it can lead to an infinite loop. I think the best way is just to not expect it to be immediately applied or to call cyclic.run() manually.

**Comment by kof** [comment]
Thats why we have  a run loop at all - cyclic dependencies.

**Comment by kof** [comment]
I will fix the example in readme as it shows it in a sync way and its wrong.
