### ISSUE TITLE
Setters vs cyclic.

### ISSUE THREAD

**Issue by trusktr** [kof/cyclic#4]
Hello @kof,

I've been making progress little by little on [Infamous](https://infamous.io/). With the API, we can do something like this:

``` html
<motor-scene>
  <motor-node id="foo" position="100,200,300" ...>
  </motor-node>
</motor-scene>
```

``` js
import Motor from 'infamous/motor/Motor'

let node = document.querySelector('#foo')
let angle = 0
Motor.addRenderTask(time => {
  angle += 1
  node.rotation = [0, angle, 0]
  // node.rotation.y = angle // this form not pushed yet, WIP, pending discussion here.
})
```

Render tasks are called once per animation frame. The Motor knows which nodes need to be re-rendered because `node.rotation`, `node.position`, etc, are setters that cause a mechanism to tell the Motor that the node need re-rendering. The re-rendering stack is executed after the render-task stack is executed. 

What I am wondering: maybe instead of setters I can use cyclic, and wonder what the pros and cons might be. If I were to use cyclic, I would hook into the Motor's animation loop by detecting changes with cyclic instead of via my Node#<setters>. I believe cyclic.Model#on handlers are sychronous (right?) which means then I can simply have Motor call `cyclic.run()` after all render tasks are executed, and then listen to the changes from `cyclic.run()` to have the nodes tell Motor they need re-rendering. 

I think I can try to list pros/cons:

Pros:
1. render tasks can execute faster because properties can all be static instead of setters/getters.
1. changes are all detected at the same time instead of spread across render tasks.

Cons:
1.Does above render task speed increase get outweighed by change detection algorithm or any other parts of cyclic?

What other pros/cons may there be in general about cyclic that I haven't thought about?

**Comment by kof** [comment]
Thats a tough question considered I barely understand your context and your bottlenecks. Also consider this lib as an experiment, I am not actually using it.

**Comment by trusktr** [comment]
Oh, and does cyclic detect changes to properties more than one level deep?

I am wondering because I'm changing my API so we can do

``` js
node.rotation.y = angle
```

as well as

``` js
node.rotation = {y: angle}
```

so both `rotation` and `rotation.y` would in my case need to be setters/getters, which makes the implementation of these nested getters/setters possibly tedious and hard to maintain. I am wonder if cyclic can detect changes more than one level deep as that might possibly increase code readability and maintainability.

**Comment by trusktr** [comment]
> Also consider this lib as an experiment, I am not actually using it.

I really like the idea, so willing to experiment with it. :]

**Comment by kof** [comment]
it connects only props you define.

**Comment by trusktr** [comment]
Aha, I just thought of a serious con: My current API allow someone to do `node.rotation = [...]` outside of a render task (for example they might naively use setInterval to make a loop, or some other mechanism, or no loop at all, just a one-off manipulation), and the setting of the value (it's a setter) trigger Motor to start the animation loop in order to re-render the Node). 

(when nothing is modified, no Motor loop runs at all, 0% CPU).

**Comment by trusktr** [comment]
If I were to have a continuous loop (my goal is to have no animationFrame at all when nothing needs animating), then I could see how cyclic would pick up changes, but if I avoid setters/getters, then I don't see a way to trigger the animation loop when `node.rotation` is set outside of a render task. I might not be able to use Cyclic without still requiring setters/getters (which is what I was trying to do), so I think I'll close this for now unless I think of something.
